"""
Django settings for segmentation_system project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

#  Django 项目配置文件，
# 用于定义项目的关键设置，包括数据库、应用注册、模板、静态文件、语言、时区以及第三方库的相关配置
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 定义了 Django 项目的根目录路径
# __file__ 是 Python 内置变量，表示当前脚本文件的路径
# resolve()将__file__ 转换为绝对路径，并解析可能存在的符号链接
# 通过两次 .parent 操作，BASE_DIR 的值是项目的根目录
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY 是 Django 项目中的一个重要配置项，用于确保项目的安全性。它在 Django 的各种加密功能中起核心作用
SECRET_KEY = "django-insecure-+zorwozcx*r8bn3@v-)j@8u1e3czvjcv9l$=7)wkzyps0ft7e$"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['172.29.32.22']


# Application definition

INSTALLED_APPS = [
    "simpleui",
    "import_export",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 自定义应用
    "instance_segmentation",  # 图像实例分割
    "feedback",  # 问题反馈
    "history",  # 历史记录管理
    "django_cleanup.apps.CleanupConfig",  # 图像更新时自动删除旧有文件, 必须放在最后
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 自定义中间件
    "middleware.current_user.CurrentUserMiddleware",
]

ROOT_URLCONF = "segmentation_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],  # 指定模板路径
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "segmentation_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

# 去除密码设置限制
AUTH_PASSWORD_VALIDATORS = [
    # {
    #     "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"  # 系统语言

TIME_ZONE = "Asia/Shanghai"  # 时区

USE_I18N = True

# USE_TZ = True  # 若不注释掉, timezone.now()获取的时间不对.


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# 静态资源
# 设置静态目录
STATIC_ROOT = BASE_DIR / "static"
# 设置静态资源地址
STATICFILES_DIRS = [
    BASE_DIR / "common_static",
]
STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# simpleui设置
# 首页标题
SIMPLEUI_HOME_TITLE = "奶山羊图像实例分割系统"
# 首页是否显示服务器、python、django、simpleui相关信息
SIMPLEUI_HOME_INFO = False
# 首页是否显示快速操作
SIMPLEUI_HOME_QUICK = True
# 首页是否显示最近动作
SIMPLEUI_HOME_ACTION = True
# simpleui自定义logo
SIMPLEUI_LOGO = "https://bkimg.cdn.bcebos.com/pic/f603918fa0ec08fa513dc97f71bc2a6d55fbb3fb6c92?x-bce-process=image/resize,m_lfit,w_536,limit_1"
# 是否允许simpleui进行使用分析
SIMPLEUI_ANALYSIS = False
# 指定simple默认的主题
SIMPLEUI_DEFAULT_THEME = "x-green.css"
# 指定simpleui是否以脱机模式加载静态资源
SIMPLEUI_STATIC_OFFLINE = True
# 自定义simpleui菜单
SIMPLEUI_CONFIG = {
    "system_keep": False,  # 是否在自定义菜单的基础上保留系统模块
    "menu_display": ["图像实例分割", "历史记录管理", "用户管理", "问题反馈"],  # 需要和menus中的names对应
    "menus": [
        {
            "name": "图像实例分割",
            "icon": "fa-regular fa-circle-nodes",
            "models": [
                {
                    "name": "奶山羊图像",
                    "icon": "el-icon-picture",
                    "url": "instance_segmentation/image/",
                }
            ],
        },
        {
            "name": "问题反馈",
            "icon": "fa-solid fa-comments",
            "models": [
                {
                    "name": "反馈意见",
                    "icon": "fa-regular fa-comment-dots",
                    "url": "feedback/feedback/",
                }
            ],
        },
        {
            "name": "历史记录管理",
            "icon": "fa-solid fa-clock-rotate-left",
            "models": [
                {
                    "name": "操作记录",
                    "icon": "fa-regular fa-calendar",
                    "url": "history/record/",
                }
            ],
        },
        {
            # 系统自带模块
            "app": "auth",
            "name": "用户管理",
            "icon": "fas fa-user-shield",
            "models": [
                {"name": "用户", "icon": "fa-solid fa-user", "url": "auth/user/"},
                {"name": "组", "icon": "fa-solid fa-user-group", "url": "auth/group/"},
            ],
        },
    ],
}
# 图标设置
# 设置系统app的默认图标，不要求与SIMPLEUI_CONFIG中保持一致
SIMPLEUI_ICON = {
    "图像实例分割": "fa-regular fa-circle-nodes",
    "奶山羊图像": "el-icon-picture",
    "问题反馈": "fa-solid fa-comments",
    "反馈意见": "fa-regular fa-comment-dots",
    "历史记录管理": "fa-solid fa-clock-rotate-left",
    "操作记录": "fa-regular fa-calendar",
}

# 媒体设置
# 设置媒体目录
MEDIA_ROOT = BASE_DIR / "media"
# 设置媒体前缀
MEDIA_URL = "/media/"

# 临时文件存储目录
FILE_UPLOAD_TEMP_DIR = BASE_DIR / "temp"
